#!/bin/bash
hg_root=$(pwd -P 2>/dev/null || command pwd)
while [ ! -e "$hg_root/.hg" ]; do
        hg_root=${hg_root%/*}
        if [ "$hg_root" = "" ]; then
                hg_root=$PWD
                break;
        fi
done

docker run -it --rm \
	--net=host \
	-v "$HOME"/.hgrc:/home/developer/.hgrc \
	-v "$hg_root"/:/home/developer/workspace/ \
	-v "$HOME"/.ssh/:/home/developer/.ssh/ \
	-v /tmp/.X11-unix/:/tmp/.X11-unix/ \
        -e DISPLAY=$DISPLAY \
	-v /usr/share/fonts/:/usr/share/fonts/ \
	rodrigomiguele/hg:base-plugins "$@"
